bank_admin/urls.py
from django.urls import path
from . import views
from .bank_admin_views import bank_admin_views
from .customer_views import customer_views
from .teller_views import teller_views
from .front_desk_views import front_desk_views
from .admin_transfer_views import admin_transfer_views
from .teller_transfer_views import teller_transfer_views
from .customer_to_customer_transfer_views import customer_to_customer_transfer_views


app_name = 'bank_admin'
urlpatterns = [
    path('', views.index, name='index'),
    # =======================Bank-Admin=============================#
    path('bank-admin/<uuid:admin>/', bank_admin_views.bankAdmin, name='bank-admin'),
    path('admin-register/', bank_admin_views.bankAdminRegister,
         name='admin-register'),
    path('login-admin/', bank_admin_views.LoginAdmin, name='login-admin'),
    path('admin-logout/<uuid:token>/',
         bank_admin_views.AdminLogout, name='admin-logout'),

    path('bank-admin-account-detail/<uuid:token>/', bank_admin_views.BankAdminAccountDetail,
         name='bank-admin-account-detail'),
    path('bank-admin-account-update/', bank_admin_views.BankAdminUpdateAccount,
         name='bank-admin-account-update'),
    path('bank-admin-update-status/<uuid:token>/', bank_admin_views.BankAdminUpdateAccountStatus,
         name='bank-admin-update-status'),

    # ========================Bank-Admin Operations==========================#
    path('get-teller-account/<uuid:token>/', bank_admin_views.PageTellerAccount,
         name='get-teller-account'),

    path('teller-detail-page/', bank_admin_views.TellerDetailPage,
         name='teller-detail-page'),

    path('get-all-tellers/<uuid:token>/', bank_admin_views.AllTellerPage,
         name='get-all-tellers'),

    path('teller-action/<uuid:teller_adminid>/<uuid:token>/', bank_admin_views.TellerAction,
         name='teller-action'),

    path('block-teller/<uuid:tellerid>/<uuid:token>/', bank_admin_views.BlockTeller,
         name='block-teller'),


    path('get-teller-number/<uuid:token>/', bank_admin_views.TellerAccountHistoryForm,
         name='get-teller-number'),

    path('teller-transaction-history/', bank_admin_views.TellerAccountHistory,
         name='teller-transaction-history'),

    path('transaction-history/<uuid:token>', bank_admin_views.TransactionHistory,
         name='transaction-history'),

    path('admin-transaction-history/<uuid:token>/', bank_admin_views.AdminTransactionHistory,
         name='admin-transaction-history'),

    path('transaction-detail/<uuid:transaction_ref>/<uuid:token>/', bank_admin_views.SingleTransactionHistory,
         name='transaction-detail'),

    path('admin-transfer-detail/<uuid:transaction_ref>/<uuid:token>/', bank_admin_views.SingleAdminTransferHistory,
         name='admin-transfer-detail'),

    path('delete-transaction/<uuid:transaction_ref>/<uuid:token>/', bank_admin_views.DeleteTransaction,
         name='delete-transaction'),

    path('delete-transfer/<uuid:transaction_ref>/<uuid:token>/', bank_admin_views.DeleteTransfer,
         name='delete-transfer'),
    # ===========================================================#
    # ===============================================================#


    # ========================Front-Desk==========================#
    path('front-desk/<uuid:token>/', front_desk_views.Dashboard, name='front-desk'),
    path('front-desk-register/', front_desk_views.FrontDeskRegister,
         name='front-desk-register'),
    path('front-desk-login/', front_desk_views.FrontDeskLogin,
         name='front-desk-login'),
    path('front-desk-logout/<uuid:token>/', front_desk_views.FrontDeskLogout,
         name='front-desk-logout'),
    path('account-detail/<uuid:token>/', front_desk_views.FrontDeskAccountDetail,
         name='account-detail'),
    path('update-account/', front_desk_views.UpdateAccount,
         name='update-account'),
    path('update-status/<uuid:token>/', front_desk_views.UpdateAccountStatus,
         name='update-status'),
    # ========================Front-Desk Operations==========================#
    path('get-customer-account/<uuid:token>/', front_desk_views.PageCustomerAccount,
         name='get-customer-account'),

    path('customer-detail-page/', front_desk_views.CustomerDetailPage,
         name='customer-detail-page'),

    path('get-all-customers/<uuid:token>/', front_desk_views.AllCustomerPage,
         name='get-all-customers'),

    path('customer-action/<uuid:customer_accountid>/<uuid:token>/', front_desk_views.CustomerAction,
         name='customer-action'),

    path('block-customer/<uuid:customerid>/<uuid:token>/', front_desk_views.BlockCustomer,
         name='block-customer'),

    path('update-customer-account-form/<uuid:customerid>/<uuid:token>/', front_desk_views.CustomerUpdateForm,
         name='update-customer-account-form'),

    path('customer-update-account/', front_desk_views.UpdateCustomerAccount,
         name='customer-update-account'),

    path('get-customer-number/<uuid:token>/', front_desk_views.CustomerAccountHistoryForm,
         name='get-customer-number'),

    path('customer-transaction-history/', front_desk_views.CustomerAccountHistory,
         name='customer-transaction-history'),
    # ===========================================================#


    # =======================Bank Customer========================#
    path('dashboard/<uuid:customer>/',
         customer_views.Dashboard, name='dashboard'),
    path('customer-register/', customer_views.CustomerRegister,
         name='customer-register'),
    path('customer-login/', customer_views.CustomerLogin, name='customer-login'),
    path('customer-logout/<uuid:token>/',
         customer_views.CustomerLogout, name='customer-logout'),


    path('transaction-history/<uuid:customerid>/',
         customer_views.CustomerTransactionHistory, name='transaction-history'),

    path('transaction-history-detail/<uuid:transaction_ref>/<uuid:token>/',
         customer_views.CustomerTransactionHistoryDetail, name='transaction-history-detail'),
    # ===========================================================#


    # ======================Tellers===============================#
    path('teller-admin/<uuid:teller>/',
         teller_views.Dashboard, name='teller-admin'),
    path('teller-register/', teller_views.TellerRegister,
         name='teller-register'),
    path('teller-login/', teller_views.TellerLogin, name='teller-login'),
    path('teller-logout/<uuid:token>/',
         teller_views.TellerLogout, name='teller-logout'),

    path('teller-admin-account-detail/<uuid:token>/', teller_views.TellerAdminAccountDetail,
         name='teller-admin-account-detail'),
    path('teller-admin-account-update/', teller_views.TellerAdminUpdateAccount,
         name='teller-admin-account-update'),
    path('teller-admin-update-status/<uuid:token>/', teller_views.TellerAdminUpdateAccountStatus,
         name='teller-admin-update-status'),

    # ===========================================================#

    # ======================Admin Transfer===============================#
    path('teller-account/<uuid:token>/',
         admin_transfer_views.GetTeller, name='teller-account'),
    path('teller-number/',
         admin_transfer_views.GetTellerNumber, name='teller-number'),
    path('transfer-teller/', admin_transfer_views.TransferToTeller,
         name='transfer-teller'),


    path('add-fund/<uuid:token>/', admin_transfer_views.FundAdminAccount,
         name='add-fund'),
    path('add-fund-form/<uuid:token>/', admin_transfer_views.FundAdminAccountForm,
         name='add-fund-form'),

    # ===========================================================#

    # ======================Teller Transfer===============================#
    path('customer-account/<uuid:token>/',
         teller_transfer_views.GetCustomer, name='customer-account'),
    path('customer-detail/',
         teller_transfer_views.GetCustomerDetail, name='customer-detail'),
    path('transfer-customer/<uuid:token>/', teller_transfer_views.TransferToCustomer,
         name='transfer-customer'),

    # ===========================================================#

    # # ======================Customer To Customer Transfer===============================#
    path('receiver-account/<uuid:token>/',
         customer_to_customer_transfer_views.GetReceiver, name='receiver-account'),
    path('receiver-detail/',
         customer_to_customer_transfer_views.GetReceiversDetail, name='receiver-detail'),
    path('transfer-receiver/', customer_to_customer_transfer_views.TransferToReceiver,
         name='transfer-receiver'),

    # # ===========================================================#






]

cweb_banking_system/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_admin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

bank_admin/models.py
from django.db import models
import uuid

# Create your models here.


class BankAdmin(models.Model):
    bank_adminid = models.UUIDField(
        primary_key=False, default=uuid.uuid4, editable=False)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    password = models.CharField(max_length=500)
    refresh_token = models.CharField(
        max_length=200, default=None, blank=True, null=True)
    email = models.EmailField(max_length=50)
    image = models.ImageField(
        upload_to='images/', default=None, blank=True, null=True)
    phoneno = models.CharField(max_length=15)
    city = models.CharField(
        max_length=200, default=None, blank=True, null=True)
    address = models.CharField(
        max_length=255, default=None, blank=True, null=True)
    balance = models.IntegerField(default=0, blank=True, null=True)
    charges = models.IntegerField(default=0, blank=True, null=True)
    job_title = models.CharField(
        max_length=255, default=None, blank=True, null=True)
    createdAt = models.DateTimeField(auto_now=True)
    updatedAt = models.DateTimeField(default=None, null=True)
    #question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.email


class FrontDeskAdmin(models.Model):
    fron_deask_adminid = models.UUIDField(
        primary_key=False, default=uuid.uuid4, editable=False)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    password = models.CharField(max_length=500)
    refresh_token = models.CharField(
        max_length=200, default=None, blank=True, null=True)
    email = models.EmailField(max_length=50)
    image = models.ImageField(
        upload_to='images/', default=None, blank=True, null=True)
    phoneno = models.CharField(max_length=15)
    city = models.CharField(
        max_length=200, default=None, blank=True, null=True)
    address = models.CharField(
        max_length=255, default=None, blank=True, null=True)

    job_title = models.CharField(
        max_length=255, default=None, blank=True, null=True)
    createdAt = models.DateTimeField(auto_now=True)
    updatedAt = models.DateTimeField(default=None, null=True)
    #question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.email


class CustomerAdmin(models.Model):
    customer_accountid = models.UUIDField(
        primary_key=False, default=uuid.uuid4, editable=False)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    password = models.CharField(max_length=500)
    refresh_token = models.CharField(
        max_length=200, default=None, blank=True, null=True)
    email = models.EmailField(max_length=50)
    image = models.ImageField(
        upload_to='images/', default=None, blank=True, null=True)
    phoneno = models.CharField(max_length=15)
    city = models.CharField(
        max_length=200, default=None, blank=True, null=True)
    address = models.CharField(
        max_length=255, default=None, blank=True, null=True)
    balance = models.IntegerField(default=0, blank=True, null=True)
    imageKYC = models.ImageField(
        upload_to='images/', default=None, blank=True, null=True)
    createdAt = models.DateTimeField(auto_now=True)
    updatedAt = models.DateTimeField(default=None, null=True)
    #question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.email
    # def __str__(self):
    #     return self.email + '' + self.firstname + ' ' + self.lastname + '' + self.balance + ' ' + self.refresh_token + ' ' + self.phoneno


class TellerAdmin(models.Model):
    teller_adminid = models.UUIDField(
        primary_key=False, default=uuid.uuid4, editable=False)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    password = models.CharField(max_length=500)
    refresh_token = models.CharField(
        max_length=200, default=None, blank=True, null=True)
    email = models.EmailField(max_length=50)
    image = models.ImageField(
        upload_to='images/', default=None, blank=True, null=True)
    phoneno = models.CharField(max_length=15)
    city = models.CharField(
        max_length=200, default=None, blank=True, null=True)
    address = models.CharField(
        max_length=255, default=None, blank=True, null=True)
    balance = models.IntegerField(default=0, blank=True, null=True)
    job_title = models.CharField(
        max_length=255, default=None, blank=True, null=True)
    createdAt = models.DateTimeField(auto_now=True)
    updatedAt = models.DateTimeField(default=None, null=True)
    #question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.email
    # def __str__(self):
    #     return int(self.balance)
        # return int(self.email + '' + self.firstname + ' ' + self.lastname + '' + str(self.balance) + ' ' + str(self.#refresh_token) + ' ' + str(self.phoneno) + ' ' + str(self.teller_adminid))


class Transactions(models.Model):
    deposit = models.IntegerField(default=0, blank=True, null=True)
    withdrawal = models.IntegerField(default=0, blank=True, null=True)
    charges = models.IntegerField(default=0, blank=True, null=True)
    fullname = models.CharField(max_length=200)
    phoneno = models.CharField(max_length=200)
    transaction_ref = models.UUIDField(
        primary_key=False, default=uuid.uuid4, editable=False)
    teller_adminid = models.CharField(max_length=200)
    customer_accountid = models.CharField(max_length=200)
    createdAt = models.DateTimeField(auto_now=True)
    updatedAt = models.DateTimeField(default=None, null=True)


class Charges(models.Model):
    withdrawal = models.IntegerField(default=0)
    charges = models.IntegerField(default=0)
    fullname = models.CharField(max_length=200)
    phoneno = models.CharField(max_length=200)
    transaction_ref = models.UUIDField(
        primary_key=False, default=uuid.uuid4, editable=False)
    customer_accountid = models.CharField(max_length=200)
    createdAt = models.DateTimeField(auto_now=True)
    updatedAt = models.DateTimeField(default=None, null=True)


class AdminTransfer(models.Model):
    balance = models.IntegerField(default=0, blank=True, null=True)
    fullname = models.CharField(max_length=200)
    phoneno = models.CharField(max_length=200)
    transaction_ref = models.UUIDField(
        primary_key=False, default=uuid.uuid4, editable=False)
    bank_adminid = models.CharField(max_length=200)
    teller_adminid = models.CharField(max_length=200)
    createdAt = models.DateTimeField(auto_now=True)
    updatedAt = models.DateTimeField(default=None, null=True)

bank_admin/templates/bank_admin/add-fund-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" href="{% static 'bank_admin/add-fund.css' %}"> 
</head>
<body>

<header class="header">
  <div class="site_logo">
    <a class="logo_link" href="{% url 'bank_admin:index' %}">
      <img src="../../../../../media/images/credit-card.png" class="logo__img" />
      Cweb-Pay 
    </a>
  </div>

   <div class="greeting">
    <div>welcome: {{firstname}} {{lastname}}</div>
    <div>Charge Inflow:  N{{charges}}</div>
    <div>bal: N{{balance}}</div>
   
   </div>
 
  <div class="register_login">
    <div class="logout">
      <a class="logout__link" href="{% url 'bank_admin:admin-logout' token %}">Logout</a>
    </div>
  </div>
</header>
<main class="container">
  <div class="greeting-small">
    <div>welcome: {{firstname}} {{lastname}}</div>
    <div>Charge Inflow:  N{{charges}} </div>
    <div>bal: N{{balance}}</div>
   
   </div>
  <div class="main-box">
    {% block content %}
    <div class="admin-items-box">
      <div class="dashboard_link-wrap">
        <a href="{% url 'bank_admin:bank-admin' token %}" class="dashboard__link">Dashboard</a>
      </div>
      <div class="teller-balance">
      <h1 >Get Customer Info</h1>
    </div>
    <div class="admin__form-container">
      <form  action= "{% url 'bank_admin:add-fund' token %}" method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="error">
          {%  if error_message %}
          <p>
            <strong class="error_message">
            {{ error_message }}
          </strong>
          </p>
          
          {% endif %}
        </div>

        <div class="form-group-parent2">
            <div class="input_parent">
              <input
                type="number"
                id="amount"
                name="amount"
                placeholder="Amount"
                class="form-control"
                value= ''
                
                />
              <label for="phoneno" class="labText">Amount</label>
            </div>
            <div class="help_parent"><span class="help-block"></span></div>
          </div>
        <div>
          <button type="submit" class="submit">Add Fund</button>
        </div>
    </form>
</div>
  </div>

  {% endblock %}
  </div>
</main>
<footer class="footer">
  <div class="contact__us">
    <a class="whatsappme" href="https://wa.me/message/Q5U5MFFUW6NVO1">
      Contact
    </a>
  </div>
  <div class="policy">
    <p class="site_policy">
      Site policy is  work in progress
    </p>
  </div>
</footer>

</body>
</html>

bank_admin/templates/bank_admin/all-teller-page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" href="{% static 'bank_admin/all-teller-page.css' %}"> 
</head>
<body>

<header class="header">
  <div class="site_logo">
    <a class="logo_link" href="{% url 'bank_admin:index' %}">
      <img src="../../../../../media/images/credit-card.png" class="logo__img" />
      Cweb-Pay 
    </a>
  </div>

   <div class="greeting">
    <div>welcome: {{firstname}} {{lastname}}</div>
    <div>Charge Inflow:  N{{charges}}</div>
    <div>bal: N{{balance}}</div>
   
   </div>
 
  <div class="register_login">
    <div class="logout">
      <a class="logout__link" href="{% url 'bank_admin:admin-logout' token %}">Logout</a>
    </div>
  </div>
</header>
<main class="container">
  <div class="greeting-small">
    <div>welcome: {{firstname}} {{lastname}}</div>
    <div>Charge Inflow:  N{{charges}} </div>
    <div>bal: N{{balance}}</div>
   
   </div>
  <div class="main-box">
    {% block content %}
    <div class="admin-items-box">
      <div class="dashboard_link-wrap">
        <a href="{% url 'bank_admin:bank-admin' token %}" class="dashboard__link">Dashboard</a>
      </div>
      <div class="teller-balance">
    
      <h1>Tellers:</h1>
    </div>
      <div class="table-items">
        <table>
          <thead>
            <tr>
              <th>Picture</th>
              <th>Firstname</th>
              <th>Lastname</th>
              <th>Teller ID</th>
              <th>Acoount No</th>
              <th>City</th>
              <th>Address</th>
              <th>Email</th>
              <th>Date Created</th>
              <th>Balance</th>
              <th>View</th>

            </tr>
            <tbody>
              {% for data in data %}
              <tr>
                <td>
                  <img src="../../../../../media/{{data.image}}" class="img-responsive" style="width: 6%; float: left; margin-right: 10px;" />
                </td>
                <td>{{data.firstname}}</td>
                <td>{{data.lastname}}</td>
                <td>{{data.teller_adminid}}</td>
                <td> {{data.phoneno}}</td>
                <td>{{data.city}}</td>
                <td>{{data.address}}</td>
                <td>{{data.email}}</td>
                <td>{{data.createdAt}}</td>
                <td>{{data.balance}}</td>
                <td>
                  <button>
                    <a href="{% url 'bank_admin:teller-action' data.teller_adminid token %}">View</a>
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </thead>
        </table>
      </div>

  </div>

  {% endblock %}
  </div>
</main>
<footer class="footer">
  <div class="contact__us">
    <a class="whatsappme" href="https://wa.me/message/Q5U5MFFUW6NVO1">
      Contact
    </a>
  </div>
  <div class="policy">
    <p class="site_policy">
      Site policy is  work in progress
    </p>
  </div>
</footer>

</body>
</html>











bank_admin/templates/bank_admin/bank-admin-account-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" href="{% static 'bank_admin/bank-admin-account-detail.css' %}"> 
</head>
<body>

<header class="header">
  <div class="site_logo">
    <a class="logo_link" href="{% url 'bank_admin:index' %}">
      <img src="../../../../../media/images/credit-card.png" class="logo__img" />
      Cweb-Pay 
    </a>
  </div>

   <div class="greeting">
    <div>welcome: {{firstname}} {{lastname}}</div>
    <div>Charge Inflow:  N{{charges}}</div>
    <div>bal: N{{balance}}</div>
   
   </div>
 
  <div class="register_login">
    <div class="logout">
      <a class="logout__link" href="{% url 'bank_admin:admin-logout' token %}">Logout</a>
    </div>
  </div>
</header>
<main class="container">
  <div class="greeting-small">
    <div>welcome: {{firstname}} {{lastname}}</div>
    <div>Charge Inflow:  N{{charges}} </div>
    <div>bal: N{{balance}}</div>
   
   </div>
  <div class="main-box">
    {% block content %}
    <div class="admin-items-box">
      <div class="dashboard_link-wrap">
        <a href="{% url 'bank_admin:bank-admin' token %}" class="dashboard__link">Dashboard</a>
      </div>
      <div class="teller-balance">
      <h1 >Account Update</h1>
    </div>
    <div class="admin__form-container">
    <form  action= "{% url 'bank_admin:bank-admin-account-update'  %}" method = "post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="error">
        {%  if error_message %}
        <p>
          <strong class="error_message">
          {{ error_message }}
        </strong>
        </p>
        
        {% endif %}
      </div>

      <div class="form-group-parent2">
          <div class="input_parent">
            <input
              type="text"
              id="city"
              name="city"
              placeholder="City"
              class="form-control"
              value= ''
              
              />
            <label for="city" class="labText">City</label>
          </div>
          <div class="help_parent"><span class="help-block"></span></div>
        </div>

        <div class="form-group-parent2">
          <div class="input_parent">
            <input
              type="text"
              id="address"
              name="address"
              placeholder="Address"
              class="form-control"
              value= ''
              
              />
            <label for="address" class="labText">Address</label>
          </div>
          <div class="help_parent"><span class="help-block"></span></div>
        </div>

        <div class="form-group-parent2">
          <div class="input_parent">
            <input
              type="text"
              id="jobtitle"
              name="jobtitle"
              
              placeholder="Job Title"
              class="form-control"
              value= ''
             
               />
            <label for="jobtitle" class="labText">Job Title</label>
          </div>
          <div class="help_parent"> <span class="help-block"></span></div>
        </div>

    

        <div class="form-group-parent2">
          <div class="input_parent">
            <input
              type="hidden"
              name="email"
              id="email"
              value= {{email}}
              />
          </div>
        </div>
        <div class="form-group-parent2">
          <div class="input_parent">
            <input
              type="hidden"
              name="token"
              id="email"
              value= {{token}}
              />
          </div>
        </div>
        <!-- <div class="form-group-parent-file">
          <div class="fileBtn_parent">
            <input  type="file" name='file' id="imgprev" /> 
            </div>
            <div class="img_parent">
            <img
            class="img_content"
            name="image"
            alt='avatarimg' 
            thumbnail
            src="URL.createObjectURL(imageprev)"
            id="profileDisplay" />
            
            </div>
          </div> -->

      <div>
        <button type="submit" class="submit">Send</button>
      </div>
  </form>
</div>
  </div>

  {% endblock %}
  </div>
</main>
<footer class="footer">
  <div class="contact__us">
    <a class="whatsappme" href="https://wa.me/message/Q5U5MFFUW6NVO1">
      Contact
    </a>
  </div>
  <div class="policy">
    <p class="site_policy">
      Site policy is  work in progress
    </p>
  </div>
</footer>

</body>
</html>



bank_admin/templates/bank_admin/bank-admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" href="{% static 'bank_admin/bank_admin.css' %}"> 
</head>
<body>


<header class="header">
  <div class="site_logo">
    <a class="logo_link" href="{% url 'bank_admin:index' %}">
      <img src="../../../../../media/images/credit-card.png" class="logo__img" />
      Cweb-Pay 
    </a>
  </div>

   <div class="greeting">
    <div>welcome: {{firstname}} {{lastname}}</div>
    <div>Charge Inflow:  N{{charges}}</div>
    <div>bal: N{{balance}}</div>
   
   </div>
 
  <div class="register_login">
    <div class="logout">
      <a class="link__item" href="{% url 'bank_admin:admin-logout' token %}">Logout</a>
    </div>
  </div>
</header>
<main class="container">
  <div class="greeting-small">
    <div>welcome: {{firstname}} {{lastname}}</div>
    <div>Charge Inflow:  N{{charges}} </div>
    <div>bal: N{{balance}}</div>
   
   </div>
  <div class="main-box">
    {% block content %}

    <div class="admin-items-box">
      <a href="{% url 'bank_admin:add-fund-form' token %}" class="items-box-link">Add Fund</a>
    </div>

    <div class="admin-items-box">
      <a href="{% url 'bank_admin:teller-account' token %}" class="items-box-link">Transfer</a>
    </div>

    
  <div class="admin-items-box">
    <a href="{% url 'bank_admin:bank-admin-account-detail' token %}" class="items-box-link">Update Account</a>
  </div>

  <div class="admin-items-box">
    <a href="{% url 'bank_admin:get-teller-account' token %}" class="items-box-link">Get Teller Info</a>
  </div>

  <div class="admin-items-box">
    <a href="{% url 'bank_admin:get-all-tellers' token %}" class="items-box-link">Get All Teller</a>
  </div>

  <div class="admin-items-box">
    <a href="{% url 'bank_admin:get-teller-number' token %}" class="items-box-link">Transaction History</a>
  </div>

  <div class="admin-items-box">
    <a href="{% url 'bank_admin:transaction-history' token %}" class="items-box-link">All Transaction History</a>
  </div>

  <div class="admin-items-box">
    <a href="{% url 'bank_admin:admin-transaction-history' token %}" class="items-box-link">Admin Transaction History</a>
  </div>

  {% endblock %}
  </div>
</main>
<footer class="footer">
  <div class="contact__us">
    <a class="whatsappme" href="https://wa.me/message/Q5U5MFFUW6NVO1">
      Contact
    </a>
  </div>
  <div class="policy">
    <p class="site_policy">
      Site policy is  work in progress
    </p>
  </div>
</footer>

</body>
</html>
